<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RH3USD0" failures="0" tests="9" name="test.day3" time="0.118" errors="1" timestamp="2024-03-03T09:56:23 IST" skipped="0">
  <testcase classname="test.day3" name="WebloginCarLoannew" time="0.000">
    <error message="
Parameter &#039;URL1&#039; is required by @Test on method WebloginCarLoannew but has not been marked @Optional or defined
in C:\Users\HP\Desktop\New folder\Selproj\testng.xml" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Parameter 'URL1' is required by @Test on method WebloginCarLoannew but has not been marked @Optional or defined
in C:\Users\HP\Desktop\New folder\Selproj\testng.xml
at org.testng.internal.Parameters.createParams(Parameters.java:270)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:358)
at org.testng.internal.Parameters.createParameters(Parameters.java:700)
at org.testng.internal.Parameters.handleParameters(Parameters.java:884)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- WebloginCarLoannew -->
  <system-out/>
  <testcase classname="test.day3" name="MobilesignoutCarLoan" time="0.030"/>
  <system-out/>
  <testcase classname="test.day3" name="WebloginCarLoan" time="0.004"/>
  <system-out/>
  <testcase classname="test.day3" name="LoginAPICarLoan" time="0.020"/>
  <system-out/>
  <testcase classname="test.day3" name="Mobilesignout1CarLoan" time="0.006"/>
  <system-out/>
  <testcase classname="test.day3" name="MobilesigninCarLoan" time="0.014"/>
  <system-out/>
  <testcase classname="test.day3" name="MobilesignoutCarLoanjihjh" time="0.032"/>
  <system-out/>
  <testcase classname="test.day3" name="MobilesignoutCarLoanjihjh" time="0.003"/>
  <system-out/>
  <testcase classname="test.day3" name="MobilesignoutCarLoanjihjh" time="0.009"/>
  <system-out/>
</testsuite> <!-- test.day3 -->
